FROM flink:1.18.1
ADD --chown=flink:flink https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.18/flink-connector-jdbc-3.2.0-1.18.jar /opt/flink/lib/flink-connector-jdbc-3.2.0-1.18.jar
ADD --chown=flink:flink https://jdbc.postgresql.org/download/postgresql-42.7.3.jar /opt/flink/lib/postgresql-42.7.3.jar